package javadatabasee;

import javadatabasee.MahasiswaDAO;
import javadatabasee.MahasiswaModel;
import javadatabasee.Mahasiswaa;
import javadatabasee.MahasiswaReguler;
import javadatabasee.MahasiswaBeasiswa;
import javadatabasee.MahasiswaInternasional;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;

public class MainFrame extends javax.swing.JFrame {

    private int rowEdit = -1;
    DefaultTableModel modelMahasiswa;
    boolean isEdit;
    private int editRowIndex;
    private Object txtfNama;
    private Mahasiswaa mahasiswa;

    private Connection conn;
    private PreparedStatement pstmt;
    private Statement stmt;

    String driver = "org.postgresql.Driver";
    String koneksi = "jdbc:postgresql://localhost:5432/Kulyeahh";
    String user = "postgres";
    String password = "salsa03";
    InputStreamReader inputStreamReader = new InputStreamReader(System.in);
    BufferedReader input = new BufferedReader(inputStreamReader);

    public MainFrame() {
        initComponents();
        txtSks.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hitungBiaya();
            }
        });

        txtTahunMasuk.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hitungBiaya();
            }
        });

        String[] kolom = {
            "Nama",
            "NIM",
            "Jenis",
            "SKS",
            "Tahun Masuk",
            "Biaya Kuliah"
        };
        modelMahasiswa = new DefaultTableModel(kolom, 0);
        tblMahasiswa.setModel(modelMahasiswa);
        isEdit = false;
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNama = new javax.swing.JLabel();
        lblNim = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNim = new javax.swing.JTextField();
        btnUpload = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMahasiswa = new javax.swing.JTable();
        lblJenis = new javax.swing.JLabel();
        cbJenis = new javax.swing.JComboBox<>();
        lblSks = new javax.swing.JLabel();
        txtSks = new javax.swing.JTextField();
        lblTahunMasuk = new javax.swing.JLabel();
        txtTahunMasuk = new javax.swing.JTextField();
        lblBiayaKuliah = new javax.swing.JLabel();
        txtBiayaKuliah = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        lblNama.setText("Masukkan Nama");

        lblNim.setText("Masukkan NIM");

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tblMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMahasiswa);

        lblJenis.setText("Jenis");

        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Jenis Mahasiswa--", "Mahasiswa Reguler", "Mahasiswa Beasiswa", "Mahasiswa Internasional" }));
        cbJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenisActionPerformed(evt);
            }
        });

        lblSks.setText("SKS");

        txtSks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSksActionPerformed(evt);
            }
        });

        lblTahunMasuk.setText("Tahun Masuk");

        txtTahunMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTahunMasukActionPerformed(evt);
            }
        });

        lblBiayaKuliah.setText("Biaya Kuliah");

        txtBiayaKuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBiayaKuliahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBiayaKuliah)
                                    .addComponent(lblJenis)
                                    .addComponent(lblTahunMasuk))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNim)
                                    .addComponent(txtNama)
                                    .addComponent(txtSks)
                                    .addComponent(txtTahunMasuk)
                                    .addComponent(txtBiayaKuliah, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                                    .addComponent(cbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnUpload)
                                    .addComponent(lblNim, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblSks))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNim)
                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSks))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJenis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTahunMasuk)
                    .addComponent(txtTahunMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBiayaKuliah)
                    .addComponent(txtBiayaKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnEdit)
                    .addComponent(btnTambah)
                    .addComponent(btnUpload))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String nim = txtNim.getText().trim();
        String nama = txtNama.getText().trim();
        String jenis = cbJenis.getSelectedItem().toString();
        int sks = Integer.parseInt(txtSks.getText());
        int tahunMasuk = Integer.parseInt(txtTahunMasuk.getText());
        double biaya = Double.parseDouble(txtBiayaKuliah.getText());

        // ====== VALIDASI ======
        if (nim.isEmpty() || nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "NIM dan Nama wajib diisi");
            return;
        }

       if (cbJenis.getSelectedIndex() == 0) {
    JOptionPane.showMessageDialog(
        this,
        "Silakan pilih jenis mahasiswa terlebih dahulu!",
        "Peringatan",
        JOptionPane.WARNING_MESSAGE
    );
    cbJenis.requestFocus();
    return;
}


        try {
            Class.forName(driver);
            conn = DriverManager.getConnection(koneksi, user, password);

            String sql = """
            INSERT INTO public."Mahasiswaaa"
            ("NIM","Nama","Jenis","SKS","TahunMasuk","BiayaKuliah")
            VALUES (?,?,?,?,?,?)
        """;

            pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, nim);
            pstmt.setString(2, nama);
            pstmt.setString(3, jenis);
            pstmt.setInt(4, sks);
            pstmt.setInt(5, tahunMasuk);
            pstmt.setDouble(6, biaya);

            pstmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil disimpan");

            // ====== TAMPILKAN KE TABEL ======
            Object[] row = {nama, nim, jenis, sks, tahunMasuk, biaya};
            modelMahasiswa.addRow(row);

            // ====== RESET FORM ======
            txtNim.setText("");
            txtNama.setText("");
            txtSks.setText("");
            txtTahunMasuk.setText("");
            txtBiayaKuliah.setText("");
            cbJenis.setSelectedIndex(0);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int selectedRow = tblMahasiswa.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus terlebih dahulu!");
            return;
        }

        // Ambil data dari tabel
        String nim = (String) tblMahasiswa.getValueAt(selectedRow, 1);

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Apakah kamu yakin ingin menghapus data dengan NIM: " + nim + "?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            // Koneksi ke database
            Class.forName(driver);
            conn = DriverManager.getConnection(koneksi, user, password);

            // SQL DELETE
            String sql = "DELETE FROM public.\"Mahasiswaaa\" WHERE \"NIM\" = ?";
            pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, nim);

            int deleted = pstmt.executeUpdate();

            if (deleted > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus dari database!");
                // Hapus juga dari tabel GUI
                modelMahasiswa.removeRow(selectedRow);
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus! NIM tidak ditemukan di database.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (pstmt != null) {
                    pstmt.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }

    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int editRow = tblMahasiswa.getSelectedRow();
        if (editRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin diedit terlebih dahulu!");
            return;
        }

        // Ambil data dari baris yang dipilih
        String namaLama = (String) tblMahasiswa.getValueAt(editRow, 0);
        String nim = (String) tblMahasiswa.getValueAt(editRow, 1);

        // Minta input baru dari user (bisa juga langsung dari text field)
        String namaBaru = JOptionPane.showInputDialog(this,
                "Edit nama mahasiswa:", namaLama);

        if (namaBaru == null || namaBaru.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong!");
            return;
        }

        int tahunMasuk = 2025; // misalnya fix, atau bisa kamu ubah sesuai kebutuhan

        // --- koneksi database dan update ---
        try {
            Class.forName(driver);
            conn = DriverManager.getConnection(koneksi, user, password);

            String sql = "UPDATE public.\"Mahasiswaaa\" SET \"Nama\" = ?, \"TahunMasuk\" = ? WHERE \"NIM\" = ?";
            pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, namaBaru);
            pstmt.setInt(2, tahunMasuk);
            pstmt.setString(3, nim);

            int updated = pstmt.executeUpdate();

            if (updated > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
                // perbarui juga tabel GUI
                modelMahasiswa.setValueAt(namaBaru, editRow, 0);
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal diperbarui (NIM tidak ditemukan)");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (pstmt != null) {
                    pstmt.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        // Pilih file CSV dari komputer
        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(this);

        if (result != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File file = chooser.getSelectedFile();

        try {
            Class.forName(driver);
            conn = DriverManager.getConnection(koneksi, user, password);

            BufferedReader br = new BufferedReader(new FileReader(file));
            String line;

            // Lewati header CSV
            //br.readLine();
            int sukses = 0;
            int gagal = 0;

            while ((line = br.readLine()) != null) {
                if (line.trim().isEmpty()) {
                    continue;
                }

                String[] data = line.split(",");

                if (data.length < 3) {
                    gagal++;
                    continue;
                }

                String nim = data[0].trim();
                String nama = data[1].trim();
                int tahun = Integer.parseInt(data[2].trim());

                try {
                    String sql = "INSERT INTO public.\"Mahasiswaaa\" (\"NIM\", \"Nama\", \"TahunMasuk\") VALUES (?, ?, ?)";

                    pstmt = conn.prepareStatement(sql);
                    pstmt.setString(1, nim);
                    pstmt.setString(2, nama);
                    pstmt.setInt(3, tahun);
                    pstmt.executeUpdate();

                    // Masukkan ke tabel GUI
                    Object[] row = {nama, nim, tahun};
                    modelMahasiswa.addRow(row);

                    sukses++;
                } catch (SQLException ex) {
                    gagal++;
                }
            }

            br.close();

            JOptionPane.showMessageDialog(this,
                    "Upload selesai!\nSukses: " + sukses + "\nGagal: " + gagal);
            loadData();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();

        }
    }//GEN-LAST:event_btnUploadActionPerformed

    private void txtSksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSksActionPerformed
        // TODO add your handling code here:
        hitungBiaya();

    }//GEN-LAST:event_txtSksActionPerformed

    private void cbJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisActionPerformed
        hitungBiaya();

    }//GEN-LAST:event_cbJenisActionPerformed

    private void txtTahunMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTahunMasukActionPerformed
        // TODO add your handling code here:
        hitungBiaya();

    }//GEN-LAST:event_txtTahunMasukActionPerformed

    private void txtBiayaKuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBiayaKuliahActionPerformed
        // TODO add your handling code here:
        hitungBiaya();

    }//GEN-LAST:event_txtBiayaKuliahActionPerformed

    private void hitungBiaya() {
        
        if (cbJenis.getSelectedIndex() == 0) {
            txtBiayaKuliah.setText("");
            return;
        }

        if (txtSks.getText().trim().isEmpty()) {
            return;
        }
        if (txtTahunMasuk.getText().trim().isEmpty()) {
            return;
        }

        int sks;
        int tahunMasuk;

        try {
            sks = Integer.parseInt(txtSks.getText());
            tahunMasuk = Integer.parseInt(txtTahunMasuk.getText());
        } catch (NumberFormatException e) {
            txtBiayaKuliah.setText("");
            return;
        }

        String jenis = cbJenis.getSelectedItem().toString();

        if (jenis.equals("Mahasiswa Reguler")) {
            mahasiswa = new MahasiswaReguler(txtNim.getText(), txtNama.getText(), sks, tahunMasuk);
        } else if (jenis.equals("Mahasiswa Beasiswa")) {
            mahasiswa = new MahasiswaBeasiswa(txtNim.getText(), txtNama.getText(), sks, tahunMasuk);
        } else if (jenis.equals("Mahasiswa Internasional")) {
            mahasiswa = new MahasiswaInternasional(txtNim.getText(), txtNama.getText(), sks, tahunMasuk);
        } else {
            txtBiayaKuliah.setText("");
            return;
        }

        txtBiayaKuliah.setText(String.valueOf(mahasiswa.hitungBiayaKuliah()));
        txtBiayaKuliah.setEditable(false);
    }

    private void loadData() {
// Kosongkan tabel dulu
        modelMahasiswa.setRowCount(0);

        try {
            Class.forName(driver);
            conn = DriverManager.getConnection(koneksi, user, password);
            stmt = conn.createStatement();

            String sql = """
            SELECT 
                "NIM",
                "Nama",
                "Jenis",
                "SKS",
                "TahunMasuk",
                "BiayaKuliah"
            FROM public."Mahasiswaaa"
            ORDER BY "Nama"
        """;

            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                Object[] row = new Object[6];
                row[0] = rs.getString("Nama");
                row[1] = rs.getString("NIM");
                row[2] = rs.getString("Jenis");
                row[3] = rs.getInt("SKS");
                row[4] = rs.getInt("TahunMasuk");
                row[5] = rs.getDouble("BiayaKuliah");

                modelMahasiswa.addRow(row);
            }

            rs.close();
            stmt.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
            e.printStackTrace();
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpload;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBiayaKuliah;
    private javax.swing.JLabel lblJenis;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNim;
    private javax.swing.JLabel lblSks;
    private javax.swing.JLabel lblTahunMasuk;
    private javax.swing.JTable tblMahasiswa;
    private javax.swing.JTextField txtBiayaKuliah;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtSks;
    private javax.swing.JTextField txtTahunMasuk;
    // End of variables declaration//GEN-END:variables
}
